version: '3.8'

services:
  client:
    build: ./lumi.client
    ports:
      - "5173:5173"
    restart: unless-stopped
    env_file:
      - ./lumi.client/.env
    depends_on:
      - server

  server:
    build: ./lumi.server
    ports:
      - "3000:3000"
    restart: unless-stopped
    env_file:
      - ./lumi.server/.env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_bd
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 147258
      POSTGRES_DB: lumi.db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
